name: ML CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Changed to 3.11 for maximum ML library stability on cloud servers
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Prefect Training Pipeline
        # This guarantees xgb_v2.pkl exists before the API tests run!
        run: |
          python app/train_pipeline.py
        env:
          PYTHONPATH: .

      - name: Run Automated Tests
        run: |
          pytest -v
        env:
          PYTHONPATH: .
